### ISSUE TITLE
Example in the README not working

### ISSUE THREAD

**Issue by Psykopear** [ooesili/sorceress#1]
Hi ooesili!

I saw this project on `This week in Rust`, and since I wanted to build something similar to be able to control SuperCollider from whithin Rust, I'm really happy to see some of the work is already done.

I tried creating a new project and running the code in the `README.md` file and noticed that it probably isn't up to date with the repository.

I had to make some minor fixes to make it work, but in the end I could hear the sinewave generated by the running SC server.

If you'd like I can open a Pull Request to fix the example in the README, this is how I had to modify it to make it work:

```rust
use anyhow::Result;
use sorceress::{
    server::{self, Server},
    synthdef::{encoder::encode_synth_defs, SynthDef},
    ugen,
};
use std::{thread::sleep, time::Duration};

fn main() -> Result<()> {
    let server = Server::connect("127.0.0.1:57110")?;

    let sine_wave = SynthDef::new("sine_wave", |_| {
        ugen::Out::ar().channels(ugen::Pan2::ar().input(ugen::SinOsc::ar().freq(220)))
    });
    let encoded_synthdef = encode_synth_defs(vec![sine_wave]);
    server.send_sync(server::SynthDefRecv::new(&encoded_synthdef))?;

    server.send(server::SynthNew::new("sine_wave", 1))?;
    sleep(Duration::from_secs(1));

    server.reset()?;

    Ok(())
}
```

**Comment by ooesili** [comment]
Thank you for raising this! You're changes looks correct and I would greatly appreciate a PR 😃 

Out of curiosity, are you looking to do anything particular with SuperCollider and Rust?

**Comment by Psykopear** [comment]
```
Thank you for raising this! You're changes looks correct and I would greatly appreciate a PR smiley
```
PR created #2 
```
Out of curiosity, are you looking to do anything particular with SuperCollider and Rust?
```
Yes, I'm still at a prototyping stage, but I'm working on a Digital Audio Workstation GUI written in Rust (with druid).
I've used SuperCollider for live coding, and I wanted to try to use it as the audio engine for this project, and this crate is exactly what I was looking for :)
